# Generated by Django 2.2.2 on 2019-06-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('labelId', models.AutoField(primary_key=True, serialize=False)),
                ('labelName', models.TextField()),
                ('labelColorName', models.TextField()),
                ('labelColorCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.TextField()),
                ('projectColorName', models.TextField()),
                ('projectColorCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=12)),
                ('userIdentity', models.CharField(max_length=2)),
                ('userSex', models.CharField(max_length=1)),
                ('userAvatar', models.FileField(upload_to='media')),
                ('userSignature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('taskTitles', models.TextField()),
                ('taskComment', models.TextField()),
                ('taskDueDate', models.IntegerField()),
                ('taskPriority', models.IntegerField()),
                ('taskStatus', models.IntegerField()),
                ('taskProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XingZhiServer.Projects')),
                ('taskUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XingZhiServer.Users')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLabels',
            fields=[
                ('taskLabelId', models.AutoField(primary_key=True, serialize=False)),
                ('labelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XingZhiServer.Labels')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XingZhiServer.Tasks')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XingZhiServer.Users'),
        ),
        migrations.AddField(
            model_name='labels',
            name='labelUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XingZhiServer.Users'),
        ),
    ]
